### ISSUE TITLE
TypeError: timeout() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by Esperator** [mtdcr/comfoair-mqtt-bridge#4]
Debian 11 on RPi3, Python 3.9,  MQTT on another machine, asyncio-mqtt      0.12.1, pycomfoair        0.0.4.

sudo /usr/bin/python3 /usr/local/bin/comfoair-mqtt-bridge.py --broker mqtt://user:pass@IP:1883 --port /dev/ttyUSB0 --debug --hass
Sending CONNECT (u1, p1, wr1, wq2, wf1, c1, k60) client_id=b''
Received CONNACK (0, 0)
Watchdog: Starting
Watchdog: Waiting for data
Sending DISCONNECT
Traceback (most recent call last):
  File "/usr/local/bin/comfoair-mqtt-bridge.py", line 529, in <module>
    asyncio.run(main(options()))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/bin/comfoair-mqtt-bridge.py", line 477, in main
    await ComfoAirMqttBridge(cfg["port"]).run(cfg["broker"], cfg["hass"])
  File "/usr/local/bin/comfoair-mqtt-bridge.py", line 442, in run
    await self._ca.connect()
  File "/usr/local/lib/python3.9/dist-packages/comfoair/asyncio.py", line 314, in connect
    await self._reconnect()
  File "/usr/local/lib/python3.9/dist-packages/comfoair/asyncio.py", line 150, in _reconnect
    async with timeout(5, loop=self._loop):
TypeError: timeout() got an unexpected keyword argument 'loop'

**Comment by mtdcr** [comment]
Should be fixed in pycomfoair 0.1.0. Thanks for your report! Please leave a message if something is still broken.
